version: "2.1"

services:
    integrate-api:
        build: .
        tty: true
        volumes:
            - ./:/go/yawoen
        environment: 
            POSTGRES_PASSWORD: jGeiFaFCC!mP
            POSTGRES_DB_NAME: yawoen
            POSTGRES_USER: yawoen_api
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432

    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: jGeiFaFCC!mP
            POSTGRES_USER: yawoen_api
            POSTGRES_DB: yawoen
